name: design_preview
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

resolution: workspace

environment:
  sdk: ^3.7.0
  flutter: ^3.29.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
